### PR TITLE
Add GreatBarracks and GreatStable features

### PR DESCRIPTION
**Pull request by Raito-95**
Hi VINAGHOST,

I noticed that while `GreatBarracks` and `GreatStable` are already implemented in the project, they don't currently have the functionality to train units. Since I often use these buildings in my own gameplay to train troops, I’ve added the ability to train units in both `GreatBarracks` and `GreatStable`.

### Key Changes:
1. **GreatBarracks**: 
   - Added functionality to allow training of infantry units, similar to the standard `Barracks`.
2. **GreatStable**: 
   - Added functionality to allow training of cavalry units, similar to the standard `Stable`.

### Why These Changes:
I added this feature for my own use since I frequently use these buildings in the game to train troops. I wanted to share this with you in case you find it useful and would like to include it in the main project. If it fits your vision, feel free to merge it, and if not, that's perfectly fine too.

Thank you for considering my contribution! Let me know if you have any feedback or suggestions.

Best regards,  
Raito

### CODE REVIEW

**Review by vinaghost — COMMENTED** [review]
@Raito-95 did it works on your side? can you give me the screenshot on train troop section ? I want to check if this works for normal way and can work with other functions

**Comment by Raito-95** [comment]
> @Raito-95 did it works on your side? can you give me the screenshot on train troop section ? I want to check if this works for normal way and can work with other functions

The bot is currently able to distinguish whether a building qualifies as "Great" and can successfully train troops, although I have modified the interface to Traditional Chinese.
messageImage_1729927809484

**Comment by vinaghost** [comment]
lgtm, but can you let it train troop on other building together to see any conflict happen ?

**Comment by Raito-95** [comment]
> lgtm, but can you let it train troop on other building together to see any conflict happen ?

Looks like it successfully distinguishes between the five buildings and trains troops without issues. I've had this function running for a few days now, and no problems have come up so far.

messageImage_1729935800075

**Comment by vinaghost** [comment]
ok, let me fix the check so it can run on your pr

**Pull request merged**
